version: '3.8'

services:
  vote:
    image: mi-vote-app:dev
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./vote:/usr/local/app
    ports:
      - "5000:80"
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: mi-redis-app
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /usr/local/bin/redis-healthcheck.sh
      interval: 5s
    deploy:
      restart_policy:
        condition: on-failure
